/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import DAO.ProdutoDAO;
import Modelo.Produto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaac
 */
public class CadastroProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProduto
     */
    
    private ProdutoDAO prodDAO = new ProdutoDAO();
    private String pesquisaNome = "";
    
    public CadastroProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jlNome = new javax.swing.JLabel();
        jlcodRevista = new javax.swing.JLabel();
        jlCiclo = new javax.swing.JLabel();
        jlFornecedor = new javax.swing.JLabel();
        jlDesc = new javax.swing.JLabel();
        jlundMed = new javax.swing.JLabel();
        jlGram = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCodRevista = new javax.swing.JTextField();
        jtfCiclo = new javax.swing.JTextField();
        jtfFornecedor = new javax.swing.JTextField();
        jtfDesc = new javax.swing.JTextField();
        jtfGram = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jcbUndMed = new javax.swing.JComboBox<>();
        jbSalvar = new javax.swing.JButton();
        jbNovoProd = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jspExibeDados = new javax.swing.JScrollPane();
        jtProdutosCadastrados = new javax.swing.JTable();
        jlTituloPesquisarProd = new javax.swing.JLabel();
        jtfBarraPesquisarProd = new javax.swing.JTextField();
        jbPesquisarProduto = new javax.swing.JButton();
        jcbTodosProdutos = new javax.swing.JCheckBox();
        jlTitulo = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlNome.setText("Nome:");

        jlcodRevista.setText("cod. Revista:");

        jlCiclo.setText("Ciclo:");

        jlFornecedor.setText("Fornecedor:");

        jlDesc.setText("Descrição:");

        jlundMed.setText("Unid. de Medida:");

        jlGram.setText("Gramatura:");

        jlValor.setText("Valor:");

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jtfCodRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodRevistaActionPerformed(evt);
            }
        });

        jtfCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCicloActionPerformed(evt);
            }
        });

        jtfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFornecedorActionPerformed(evt);
            }
        });

        jtfDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDescActionPerformed(evt);
            }
        });

        jtfGram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfGramActionPerformed(evt);
            }
        });

        jtfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfValorActionPerformed(evt);
            }
        });

        jcbUndMed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mililitros", "Gramas" }));
        jcbUndMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUndMedActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbNovoProd.setText("Novo Cadastro");
        jbNovoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoProdActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jtProdutosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cod. Revista", "Fornecedor", "Valor", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtProdutosCadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutosCadastradosMouseClicked(evt);
            }
        });
        jspExibeDados.setViewportView(jtProdutosCadastrados);

        jlTituloPesquisarProd.setText("Pesquisar:");

        jtfBarraPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBarraPesquisarProdActionPerformed(evt);
            }
        });

        jbPesquisarProduto.setText("Pesquisar");
        jbPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarProdutoActionPerformed(evt);
            }
        });

        jcbTodosProdutos.setText("Todos");
        jcbTodosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTodosProdutosActionPerformed(evt);
            }
        });

        jlTitulo.setText("Gerenciamento de Produtos");
        jlTitulo.setName(""); // NOI18N

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jlGram)
                        .addGap(4, 4, 4)
                        .addComponent(jtfGram, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlundMed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbUndMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlDesc)
                                .addGap(4, 4, 4)
                                .addComponent(jtfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlcodRevista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCodRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValor)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCiclo)
                        .addGap(3, 3, 3)
                        .addComponent(jtfCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlTituloPesquisarProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBarraPesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jbPesquisarProduto)
                        .addGap(46, 46, 46)
                        .addComponent(jcbTodosProdutos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbNovoProd, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jspExibeDados, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jlTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlTitulo)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jlcodRevista)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCodRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCiclo)
                    .addComponent(jtfCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFornecedor)
                    .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDesc)
                    .addComponent(jtfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGram)
                    .addComponent(jtfGram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlundMed)
                    .addComponent(jcbUndMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlValor)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovoProd)
                    .addComponent(jbCancelar)
                    .addComponent(jbExcluir)
                    .addComponent(jbEditar)
                    .addComponent(jbSalvar)
                    .addComponent(jbSair))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloPesquisarProd)
                    .addComponent(jtfBarraPesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisarProduto)
                    .addComponent(jcbTodosProdutos))
                .addGap(18, 18, 18)
                .addComponent(jspExibeDados, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtfCodRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodRevistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodRevistaActionPerformed

    private void jtfCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCicloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCicloActionPerformed

    private void jtfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFornecedorActionPerformed

    private void jtfDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescActionPerformed

    private void jtfGramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfGramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfGramActionPerformed

    private void jcbUndMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUndMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbUndMedActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        Produto produto = new Produto();
        produto.setNome(jtfNome.getText());
        produto.setCodigo_revista(jtfCodRevista.getText());
        produto.setCiclo_campanha(jtfCiclo.getText());
        produto.setFornecedor(jtfFornecedor.getText());
        produto.setDescricao(jtfDesc.getText());
        produto.setQuantidade_ml(Integer.parseInt(jtfGram.getText()));
        produto.setValor(Double.parseDouble(jtfValor.getText()));
        produto.setUnidade_medida(String.valueOf(jcbUndMed.getSelectedItem()));
        
        prodDAO.inserirProduto(produto);
        limparCampos();
         //ativa botoes
        jbNovoProd.setEnabled(true);
        jbSair.setEnabled(true);
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        Produto produto = new Produto();
        produto.setId_produto(Integer.parseInt(String.valueOf(jtProdutosCadastrados.getValueAt(jtProdutosCadastrados.getSelectedRow(), 0))));
        produto.setNome(jtfNome.getText());
        produto.setCodigo_revista(jtfCodRevista.getText());
        produto.setDescricao(jtfDesc.getText());
        produto.setCiclo_campanha(jtfCiclo.getText());
        produto.setFornecedor(jtfFornecedor.getText());
        produto.setQuantidade_ml(Integer.parseInt(jtfGram.getText()));
        produto.setValor(Double.parseDouble(jtfValor.getText()));
        produto.setUnidade_medida(String.valueOf(jcbUndMed.getSelectedItem()));
        prodDAO.editarProduto(produto);
        limparCampos();
        jbNovoProd.setEnabled(true);
        jcbTodosProdutos.setSelected(false);
        jtProdutosCadastrados.setModel(new DefaultTableModel());
        
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbNovoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoProdActionPerformed
       jbSalvar.setEnabled(true);
       jbCancelar.setEnabled(true);
       jbSair.setEnabled(true);
       jbExcluir.setEnabled(false);
       jbEditar.setEnabled(false);
       jbNovoProd.setEnabled(false);
    }//GEN-LAST:event_jbNovoProdActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        //Pega o ID do produto
        prodDAO.excluirProduto(prodDAO.pesquisarProduto(jtfNome.getText()).getId_produto());
        limparCampos();
        jtProdutosCadastrados.setModel(new DefaultTableModel());
        jcbTodosProdutos.setSelected(false);
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtfBarraPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBarraPesquisarProdActionPerformed
        
    }//GEN-LAST:event_jtfBarraPesquisarProdActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        limparCampos();
        //ativa botoes
        jbNovoProd.setEnabled(true);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jtfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfValorActionPerformed

    }//GEN-LAST:event_jtfValorActionPerformed

    private void jcbTodosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTodosProdutosActionPerformed
        jtProdutosCadastrados.setModel(prodDAO.pesquisarTodos());
        if(!jcbTodosProdutos.isSelected()){
            jtProdutosCadastrados.setModel(new DefaultTableModel());
        }    
    }//GEN-LAST:event_jcbTodosProdutosActionPerformed

    private void jbPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarProdutoActionPerformed
        Produto produto = prodDAO.pesquisarProduto(jtfBarraPesquisarProd.getText());
        Object dados[] = {produto.getId_produto(),produto.getNome(),produto.getCodigo_revista(),produto.getFornecedor(),produto.getValor(),produto.getDescricao()};
        DefaultTableModel tabela = new DefaultTableModel();
        tabela.setColumnIdentifiers(new String[]{"ID","Nome","Cod. Revista","Fornecedor","Valor","Descrição"});
        tabela.addRow(dados);
        jtProdutosCadastrados.setModel(tabela);
    }//GEN-LAST:event_jbPesquisarProdutoActionPerformed

    private void jtProdutosCadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutosCadastradosMouseClicked
        String pesquisa = ""+jtProdutosCadastrados.getValueAt(jtProdutosCadastrados.getSelectedRow(), 1);
        Produto produto = prodDAO.pesquisarProduto(pesquisa);
        jtfNome.setText(produto.getNome());
        jtfCodRevista.setText(produto.getCodigo_revista());
        jtfCiclo.setText(produto.getCiclo_campanha());
        jtfDesc.setText(produto.getDescricao());
        jtfFornecedor.setText(produto.getFornecedor());
        jtfValor.setText(Double.toString(produto.getValor()));
        jcbUndMed.setSelectedItem(produto.getUnidade_medida());
        jtfGram.setText(Integer.toString(produto.quantidade_ml));
        jbEditar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbSalvar.setEnabled(false);
        jbNovoProd.setEnabled(false);
        jbExcluir.setEnabled(true);
    }//GEN-LAST:event_jtProdutosCadastradosMouseClicked
    
    
    public void limparCampos(){
        jtfNome.setText("");
        jtfCodRevista.setText("");
        jtfCiclo.setText("");
        jtfFornecedor.setText("");
        jtfDesc.setText("");
        jtfGram.setText("");
        jtfValor.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider jSlider1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovoProd;
    private javax.swing.JButton jbPesquisarProduto;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JCheckBox jcbTodosProdutos;
    private javax.swing.JComboBox<String> jcbUndMed;
    private javax.swing.JLabel jlCiclo;
    private javax.swing.JLabel jlDesc;
    private javax.swing.JLabel jlFornecedor;
    private javax.swing.JLabel jlGram;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTituloPesquisarProd;
    private javax.swing.JLabel jlValor;
    private javax.swing.JLabel jlcodRevista;
    private javax.swing.JLabel jlundMed;
    private javax.swing.JScrollPane jspExibeDados;
    private javax.swing.JTable jtProdutosCadastrados;
    private javax.swing.JTextField jtfBarraPesquisarProd;
    private javax.swing.JTextField jtfCiclo;
    private javax.swing.JTextField jtfCodRevista;
    private javax.swing.JTextField jtfDesc;
    private javax.swing.JTextField jtfFornecedor;
    private javax.swing.JTextField jtfGram;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}