/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author isaac
 */
public class Compra extends javax.swing.JFrame {

    /**
     * Creates new form Compra
     */
    public Compra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        jlTituloCompra = new javax.swing.JLabel();
        jlTituloCliente = new javax.swing.JLabel();
        jlTituloProduto = new javax.swing.JLabel();
        jlPesquisaCliente = new javax.swing.JLabel();
        jtfBarraPesquisaCliente = new javax.swing.JTextField();
        jbPesqCliente = new javax.swing.JButton();
        jcbTodosClientes = new javax.swing.JCheckBox();
        jcbTodosProdutos = new javax.swing.JCheckBox();
        jbPesqProduto = new javax.swing.JButton();
        jtfBarraPesquisaProduto = new javax.swing.JTextField();
        jlPesquisaProduto = new javax.swing.JLabel();
        jlnomeSobrenome = new javax.swing.JLabel();
        jlValorNomeSobrenome = new javax.swing.JLabel();
        jlcpfCliente = new javax.swing.JLabel();
        jlValorCPF = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jlEnderecoCompleto = new javax.swing.JLabel();
        jlTelefoneCelular = new javax.swing.JLabel();
        jlValorFones = new javax.swing.JLabel();
        jlProdutosComprados = new javax.swing.JLabel();
        jbAdicionaProduto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtProdutosComprados = new javax.swing.JTable();
        jlDadosComprador = new javax.swing.JLabel();
        jsQuantidadeProduto = new javax.swing.JSpinner();
        jlTotal = new javax.swing.JLabel();
        jbRemoveProduto = new javax.swing.JButton();
        jlQuantidade = new javax.swing.JLabel();
        jlValorTotalComprado = new javax.swing.JLabel();
        jlStatusPago = new javax.swing.JLabel();
        jcbStatusPagamento = new javax.swing.JComboBox<>();
        jbFinalizaCompra = new javax.swing.JButton();
        jbCancelaCompra = new javax.swing.JButton();
        jldataCompra = new javax.swing.JLabel();
        jlDataAtual = new javax.swing.JLabel();
        jlStatusEntrega = new javax.swing.JLabel();
        jcbStatusEntrega = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cod Revista", "Ciclo", "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProdutos);

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "CPF", "Endereço", "Fones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtClientes);

        jlTituloCompra.setText("Compra");

        jlTituloCliente.setText("Selecionar Cliente");

        jlTituloProduto.setText("Selecionar Produtos");

        jlPesquisaCliente.setText("Pesquisar:");

        jtfBarraPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBarraPesquisaClienteActionPerformed(evt);
            }
        });

        jbPesqCliente.setText("Pesquisar");

        jcbTodosClientes.setText("Todos");

        jcbTodosProdutos.setText("Todos");

        jbPesqProduto.setText("Pesquisar");

        jtfBarraPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBarraPesquisaProdutoActionPerformed(evt);
            }
        });

        jlPesquisaProduto.setText("Pesquisar:");

        jlnomeSobrenome.setText("Nome Completo:");

        jlValorNomeSobrenome.setText("nomeESobrenome");

        jlcpfCliente.setText("CPF:");

        jlValorCPF.setText("cpfCliente");

        jlEndereco.setText("Endereço:");

        jlEnderecoCompleto.setText("enderecoCliente");

        jlTelefoneCelular.setText("Fones:");

        jlValorFones.setText("telefoneECelular");

        jlProdutosComprados.setText("Produtos Comprados");

        jbAdicionaProduto.setText("Adicionar Produto");

        jtProdutosComprados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor", "Descrição"
            }
        ));
        jScrollPane3.setViewportView(jtProdutosComprados);

        jlDadosComprador.setText("Dados do Comprador");

        jlTotal.setText("Valor Total:");

        jbRemoveProduto.setText("Remover da Compra");

        jlQuantidade.setText("Quandidade:");

        jlValorTotalComprado.setText("ValorTotal");

        jlStatusPago.setText("Estado de Pagamento:");

        jcbStatusPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbFinalizaCompra.setText("Finalizar Compra");
        jbFinalizaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizaCompraActionPerformed(evt);
            }
        });

        jbCancelaCompra.setText("Cancelar");

        jldataCompra.setText("Data da Compra:");

        jlDataAtual.setText("dataAtual");

        jlStatusEntrega.setText("Entrega:");

        jcbStatusEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jlTituloCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTituloProduto)
                .addGap(177, 177, 177))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(jlTituloCompra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlPesquisaCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBarraPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPesqCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTodosClientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlPesquisaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBarraPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbPesqProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbTodosProdutos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTelefoneCelular)
                        .addGap(18, 18, 18)
                        .addComponent(jlValorFones))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlnomeSobrenome)
                        .addGap(18, 18, 18)
                        .addComponent(jlValorNomeSobrenome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlEnderecoCompleto)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlStatusEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbStatusEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlcpfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlValorCPF)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbAdicionaProduto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlStatusPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbStatusPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlTotal)
                                .addGap(18, 18, 18)
                                .addComponent(jlValorTotalComprado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbRemoveProduto))
                            .addComponent(jScrollPane3))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFinalizaCompra)
                .addGap(112, 112, 112)
                .addComponent(jbCancelaCompra)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jlDadosComprador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlProdutosComprados)
                .addGap(163, 163, 163))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jldataCompra)
                .addGap(18, 18, 18)
                .addComponent(jlDataAtual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlTituloCompra)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesquisaCliente)
                            .addComponent(jtfBarraPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPesqCliente)
                            .addComponent(jcbTodosClientes)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTituloCliente)
                            .addComponent(jlTituloProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPesquisaProduto)
                            .addComponent(jtfBarraPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPesqProduto)
                            .addComponent(jcbTodosProdutos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidade)
                    .addComponent(jlStatusPago)
                    .addComponent(jcbStatusPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbAdicionaProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProdutosComprados)
                    .addComponent(jlDadosComprador))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlnomeSobrenome)
                            .addComponent(jlValorNomeSobrenome)
                            .addComponent(jlcpfCliente)
                            .addComponent(jlValorCPF))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEndereco)
                            .addComponent(jlEnderecoCompleto))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelefoneCelular)
                            .addComponent(jlValorFones)
                            .addComponent(jlStatusEntrega)
                            .addComponent(jcbStatusEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTotal)
                            .addComponent(jlValorTotalComprado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbRemoveProduto)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jldataCompra)
                    .addComponent(jlDataAtual))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbFinalizaCompra)
                    .addComponent(jbCancelaCompra)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBarraPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBarraPesquisaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBarraPesquisaClienteActionPerformed

    private void jtfBarraPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBarraPesquisaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBarraPesquisaProdutoActionPerformed

    private void jbFinalizaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizaCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbFinalizaCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAdicionaProduto;
    private javax.swing.JButton jbCancelaCompra;
    private javax.swing.JButton jbFinalizaCompra;
    private javax.swing.JButton jbPesqCliente;
    private javax.swing.JButton jbPesqProduto;
    private javax.swing.JButton jbRemoveProduto;
    private javax.swing.JComboBox<String> jcbStatusEntrega;
    private javax.swing.JComboBox<String> jcbStatusPagamento;
    private javax.swing.JCheckBox jcbTodosClientes;
    private javax.swing.JCheckBox jcbTodosProdutos;
    private javax.swing.JLabel jlDadosComprador;
    private javax.swing.JLabel jlDataAtual;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlEnderecoCompleto;
    private javax.swing.JLabel jlPesquisaCliente;
    private javax.swing.JLabel jlPesquisaProduto;
    private javax.swing.JLabel jlProdutosComprados;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlStatusEntrega;
    private javax.swing.JLabel jlStatusPago;
    private javax.swing.JLabel jlTelefoneCelular;
    private javax.swing.JLabel jlTituloCliente;
    private javax.swing.JLabel jlTituloCompra;
    private javax.swing.JLabel jlTituloProduto;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JLabel jlValorCPF;
    private javax.swing.JLabel jlValorFones;
    private javax.swing.JLabel jlValorNomeSobrenome;
    private javax.swing.JLabel jlValorTotalComprado;
    private javax.swing.JLabel jlcpfCliente;
    private javax.swing.JLabel jldataCompra;
    private javax.swing.JLabel jlnomeSobrenome;
    private javax.swing.JSpinner jsQuantidadeProduto;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JTable jtProdutosComprados;
    private javax.swing.JTextField jtfBarraPesquisaCliente;
    private javax.swing.JTextField jtfBarraPesquisaProduto;
    // End of variables declaration//GEN-END:variables
}
